2018-02-03 06:40:06,157 INFO: Microblog startup [in C:\lren\projects\microblog\app\__init__.py:44]
2018-02-03 07:42:01,177 INFO: Microblog startup [in C:\lren\projects\microblog\app\__init__.py:44]
2018-02-03 07:47:09,814 INFO: Microblog startup [in C:\lren\projects\microblog\app\__init__.py:46]
2018-02-04 05:37:08,132 INFO: Microblog startup [in C:\lren\projects\microblog\app\__init__.py:46]
2018-02-04 05:41:18,379 INFO: Microblog startup [in C:\lren\projects\microblog\app\__init__.py:46]
2018-02-04 06:38:48,707 INFO: Microblog startup [in C:\lren\projects\microblog\app\__init__.py:46]
2018-02-04 06:41:07,364 ERROR: Exception on /reset_password_request [POST] [in c:\lren\projects\microblog\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\lren\projects\microblog\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\lren\projects\microblog\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\lren\projects\microblog\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\lren\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\lren\projects\microblog\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\lren\projects\microblog\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\lren\projects\microblog\app\routes.py", line 104, in reset_password_request
    send_password_reset_email(user)
  File "C:\lren\projects\microblog\app\email.py", line 15, in send_password_reset_email
    token = user.get_password_reset_token()
AttributeError: 'User' object has no attribute 'get_password_reset_token'
2018-02-04 06:41:30,396 ERROR: Exception on /reset_password_request [POST] [in c:\lren\projects\microblog\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\lren\projects\microblog\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\lren\projects\microblog\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\lren\projects\microblog\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\lren\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\lren\projects\microblog\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\lren\projects\microblog\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\lren\projects\microblog\app\routes.py", line 104, in reset_password_request
    send_password_reset_email(user)
  File "C:\lren\projects\microblog\app\email.py", line 15, in send_password_reset_email
    token = user.get_password_reset_token()
AttributeError: 'User' object has no attribute 'get_password_reset_token'
2018-02-04 06:57:46,288 INFO: Microblog startup [in C:\lren\projects\microblog\app\__init__.py:46]
